Add query to count content-types used for WordPress pages
GoogleChromeLabs/wpp-research pull request #74
Opened 2023-10-04 23:55 UTC by westonruter

In [discussing](https://wordpress.slack.com/archives/C05NFB818PQ/p1695770376425949) with @dmsnell in the #core-html-api Slack channel about [whether XHTML support should be removed from core](https://wordpress.slack.com/archives/C05NFB818PQ/p1695776267247279), I wanted to do a query to see how many WordPress pages are actually served with the `Content-Type` of `application/xhtml+xml`. Even when the response body contains valid XML/XHTML markup, browsers will still use the HTML parser if the `Content-Type` is `text/html`. So we can determine whether attempting to maintain valid XHTML syntax is important for WordPress by checking how often pages are returned as `application/xhtml+xml`. Presuming my query is correct, in short, the answer is very few: specifically **four**. (This is also slightly inflated because it includes both **desktop** and **mobile** visits, so there are some duplicates.) In fact, there are more pages returned as RSS or plain text than XHTML.

Content-Type | Count
-- | --:
text/html | 17,277,213
application/rss+xml | 162
text/plain | 31
text/xml | 13
-- | 9
texthtml | 9
x-httpd-php | 8
text | 8
application/xhtml+xml | 5
charset=utf-8 | 5
text/css | 5
application/json | 4
1 | 4
twentyseventeen | 4
html_type | 4
**application/atom+xml** | 4
another text/html | 4
text/HTML | 2
utf-8 | 1
Array | 1
image/png | 1

(Query elapsed time: 52 sec)

I checked the URLs that were being returned as `application/atom+xml` when crawled, and they are all returning `text/html` now.

So I think it is safe to say that WordPress can safely abandon any attempt to serve valid XML pages.

2023-10-05 21:04 UTC, felixarntz requested changes
@westonruter The query looks great, only a few minor recommendations below for improvement.

There is only one quirk which I think is crucial to fix: I think we should limit results to only those where `client = 'mobile'`, otherwise I believe we get duplicate URLs, and I assume that is currently the case. Whether mobile or desktop is used doesn't matter what we're trying to achieve here, so then I'd say we should use mobile just because the dataset is larger.

It obviously shouldn't change the ratio of the results much, but I think the numbers would be lower and more accurate.

2023-10-05 21:08 UTC, westonruter commented on sql/2023/10/page-content-types.sql
> +  pages AS (
I indented it this way so that it would be indented the same as `requests` below.

2023-10-05 21:16 UTC, westonruter commented on sql/2023/10/page-content-types.sql
> +      root_page = url
Yes, you're right: 

![image](https://github.com/GoogleChromeLabs/wpp-research/assets/134745/de046e7d-7cc2-4bfa-bb1f-dadffe82f5c5)

2023-10-05 21:38 UTC, westonruter commented
> There is only one quirk which I think is crucial to fix: I think we should limit results to only those where `client = 'mobile'`, otherwise I believe we get duplicate URLs, and I assume that is currently the case. Whether mobile or desktop is used doesn't matter what we're trying to achieve here, so then I'd say we should use mobile just because the dataset is larger.

@felixarntz I've made this change to the query. I've updated the description to reflect the changes. However, doing so exposed something surprising: I re-checked the URLs when emulating a mobile device in DevTools, and actually they are only serving valid XHTML to mobile devices. For desktop, they serve HTML. So I wonder actually if these should be considered duplicates given the possibility of content negotiation based on client type?

2023-10-26 17:07 UTC, felixarntz commented on sql/2023/10/page-content-types.sql
> +      root_page = url
This line can be removed now given `is_root_page` is already included in the `WHERE` clause.

2023-10-26 17:09 UTC, felixarntz commented on sql/2023/10/page-content-types.sql
> +      t.technology = 'WordPress'
```suggestion
    SELECT
      client,
      page AS url
    FROM
      `httparchive.all.pages`,
      UNNEST(technologies) AS t
    WHERE
      date = '2023-08-01' AND
      is_root_page AND
      t.technology = 'WordPress'
```

2023-10-26 17:10 UTC, felixarntz commented on sql/2023/10/page-content-types.sql
> +      client = 'mobile' AND
```suggestion
    SELECT
      client,
      url,
      REGEXP_REPLACE( resp_headers.value, ' *;.*$', '' ) AS content_type
    FROM
      `httparchive.all.requests`,
      UNNEST(response_headers) as resp_headers
    WHERE
      date = "2023-08-01" AND
      is_root_page AND
```

2023-10-26 18:04 UTC, westonruter commented
> Could you please apply these changes and rerun the query to update the PR description when you get a chance?

@felixarntz Query re-run and results added to PR description. Indeed the results show that only mobile clients are getting served the 4 XHTML responses.

2023-10-26 19:42 UTC, felixarntz approved these changes
@westonruter LGTM!

Is there a Trac ticket to further discuss removing non-HTML5 support? Based on this data, certainly seems reasonable.

2023-10-26 19:42 UTC, felixarntz commented on sql/2023/10/page-content-types.sql
> +  )
```suggestion
  SELECT
    client,
    page AS url
  FROM
    `httparchive.all.pages`,
    UNNEST(technologies) AS t
  WHERE
    date = '2023-08-01' AND
    is_root_page AND
    t.technology = 'WordPress'
),

# h/t https://discuss.httparchive.org/t/help-finding-list-of-home-pages-with-specific-http-response-header/2567/2
requests AS (
  SELECT
    client,
    url,
    REGEXP_REPLACE( resp_headers.value, ' *;.*$', '' ) AS content_type
  FROM
    `httparchive.all.requests`,
    UNNEST(response_headers) as resp_headers
  WHERE
    date = "2023-08-01" AND
    is_root_page AND
    lower(resp_headers.name) = 'content-type' AND
    is_main_document
)
```

2023-10-26 20:09 UTC, westonruter commented
> Is there a Trac ticket to further discuss removing non-HTML5 support? Based on this data, certainly seems reasonable.

@felixarntz No, not that I'm aware of. However, @dmsnell may be on the cusp of doing so as part of the HTML API effort, since it is somewhat the motivator for doing this in the first place.

2023-10-26 20:59 UTC, swissspidy approved these changes

2023-10-26 22:54 UTC, merged

2023-10-29 15:34 UTC, dmsnell commented
After chatting with @azozz I think I'm going to create a Trac ticket for it, but the next few days I'll be away from my work. It's all driven by the desire to know what we're allowed to change and what we _aren't_. For example, WordPress arbitrarily breaks most HTML named character references because it wants to limit the allowed set to those that were in the HTML4 spec _plus_ a few hand-picked names. For example, if you save `&RoundImplies;` in the database, it will be corrupted by `kses` and display as `&RoundImplies;` instead of as `⥰`, because `kses` turns it into `&amp;RoundImplies;`, being unaware of the HTML5 named character references. I'd like to fix these things, but it's unclear if we can make this call since it's required by HTML5 but not by HTML4